version: '3'
services:
  behappy-sentinel-dashboard:
    restart: 'always'
    privileged: true
    container_name: behappy-sentinel-dashboard
    image: wangxiaowu950330/behappy-sentinel-dashboard:v1.8.5-nacos
    # 修改环境变量
    environment:
      # JAVA_OPTS: "-Xms256m -Xmx256m -Dauth.password=123456 -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom"
      SPRING_CLOUD_SENTINEL_DATASOURCE_NACOS_SERVERADDR: 127.0.0.1:8848
      SPRING_CLOUD_SENTINEL_DATASOURCE_NACOS_USERNAME: nacos
      SPRING_CLOUD_SENTINEL_DATASOURCE_NACOS_PASSWORD: nacos
      SPRING_CLOUD_SENTINEL_DATASOURCE_NACOS_GROUPID: DEFAULT_GROUP
      SPRING_CLOUD_SENTINEL_DATASOURCE_NACOS_NAMESPACE: public
    ports:
      - "8858:8858"
    volumes:
      - /var/log/sentinel:/var/log/sentinel
